# Generated by Django 4.2.7 on 2023-11-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/blog_images"
            ),
        ),
    ]
